# Example RKE2 config for agent role
# Copy to /etc/rancher/rke2/config.yaml or use --config flag

# RKE2 server address (port 9345)
server: "https://rke2.example.com:9345"

# Cluster token (if not set via installer flags)
token: "supersecret-token"


